In [1]:
import pandas as pd

%cd "C:\Users\jwill\Documents\Machine Learning\Latent Class Analysis"

C:\Users\jwill\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\jwill\anaconda3\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\jwill\anaconda3\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

C:\Users\jwill\Documents\Machine Learning\Latent Class Analysis

In [2]:
import pandas as pd
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Number of customers
n_customers = 1000

# Purchase Frequency
purchase_frequency = np.random.choice(['Daily', 'Weekly', 'Monthly'], size=n_customers, p=[0.1, 0.4, 0.5])

# Average Purchase Amount
purchase_amount = np.random.choice(['Low', 'Medium', 'High'], size=n_customers, p=[0.5, 0.3, 0.2])

# Product Categories
product_categories = np.random.choice(['Electronics', 'Clothing', 'Groceries'], size=n_customers, p=[0.3, 0.4, 0.3])

# Payment Method
payment_method = np.random.choice(['Cash', 'Credit Card', 'Digital Wallet'], size=n_customers, p=[0.4, 0.4, 0.2])

# Customer Loyalty
customer_loyalty = np.random.choice(['Member', 'Non-Member'], size=n_customers, p=[0.3, 0.7])

# Create DataFrame
data = pd.DataFrame({
    'Purchase Frequency': purchase_frequency,
    'Average Purchase Amount': purchase_amount,
    'Product Categories': product_categories,
    'Payment Method': payment_method,
    'Customer Loyalty': customer_loyalty
})

data.head()

,Purchase Frequency,Average Purchase Amount,Product Categories,Payment Method,Customer Loyalty
0,Weekly,Low,Electronics,Credit Card,Non-Member
1,Monthly,Medium,Electronics,Credit Card,Non-Member
2,Monthly,High,Groceries,Cash,Non-Member
3,Monthly,Medium,Electronics,Credit Card,Member
4,Weekly,High,Electronics,Credit Card,Member

In [4]:
# Save to CSV
data.to_csv('synthetic_customer_data.csv', index=False)

In [5]:
# Install the stepmix library
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from stepmix.stepmix import StepMix

# Load the synthetic dataset
data = pd.read_csv('synthetic_customer_data.csv')

# Encode categorical variables
le = LabelEncoder()
data_encoded = data.apply(le.fit_transform)

# Convert to numpy array
X = data_encoded.values

# Fit StepMix model
model = StepMix(n_components=3, n_steps=1)
model.fit(X)

# Predict latent classes
latent_classes = model.predict(X)
data['Latent Class'] = latent_classes

data.head()

Fitting StepMix...

Initializations (n_init) : 100%|██████████| 1/1 [00:00<00:00, 27.37it/s, max_LL=2.71e+4, max_avg_LL=27.1]

,Purchase Frequency,Average Purchase Amount,Product Categories,Payment Method,Customer Loyalty,Latent Class
0,Weekly,Low,Electronics,Credit Card,Non-Member,0
1,Monthly,Medium,Electronics,Credit Card,Non-Member,0
2,Monthly,High,Groceries,Cash,Non-Member,0
3,Monthly,Medium,Electronics,Credit Card,Member,0
4,Weekly,High,Electronics,Credit Card,Member,0

In [6]:
data

,Purchase Frequency,Average Purchase Amount,Product Categories,Payment Method,Customer Loyalty,Latent Class
0,Weekly,Low,Electronics,Credit Card,Non-Member,0
1,Monthly,Medium,Electronics,Credit Card,Non-Member,0
2,Monthly,High,Groceries,Cash,Non-Member,0
3,Monthly,Medium,Electronics,Credit Card,Member,0
4,Weekly,High,Electronics,Credit Card,Member,0
...,...,...,...,...,...,...
995,Daily,Medium,Groceries,Credit Card,Non-Member,0
996,Monthly,High,Electronics,Cash,Member,0
997,Weekly,Low,Clothing,Cash,Non-Member,2
998,Monthly,Low,Electronics,Credit Card,Non-Member,0
999,Weekly,Low,Groceries,Cash,Non-Member,0

In [7]:
# Analyze the distribution of latent classes
class_distribution = data['Latent Class'].value_counts()
print(class_distribution)

# Group by latent class to see characteristics of each class
class_characteristics = data.groupby('Latent Class').mean()
print(class_characteristics)

0    551
1    285
2    164
Name: Latent Class, dtype: int64
Empty DataFrame
Columns: []
Index: [0, 1, 2]

<ipython-input-7-5918d80b6bb3>:6: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  class_characteristics = data.groupby('Latent Class').mean()